name: Base64 experiments
on: push

jobs:
  windows:
    name: Try base64 on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump secret to file
        shell: bash
        run: |
          echo "${{secrets.CSC_LINK}}" > certificate.pfx.base64
          cat certificate.pfx.base64 | base64 -d > certificate.pfx
          ls -l certificate*

  mac:
    name: Try base64 on Mac
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump secret to file
        run: |
          export CSC_LINK=$GITHUB_WORKSPACE/electron/certificate.pfx
          echo "${{secrets.CSC_LINK}}" > certificate.pfx.base64
          cat certificate.pfx.base64 | base64 -d > certificate.pfx
          ls -l certificate*
