name: Base64 experiments
on: push

jobs:
  windows:
    name: Try base64 on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump secret to file
        run: |
          echo "${{secrets.TEST_BASE64}}" > book.zip.base64
          type book.zip.base64 | base64 -d -i > book.zip
          unzip book.zip
          pwd
          dir book*.*

  mac:
    name: Try base64 on Mac
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump secret to file
        run: |
          echo "${{secrets.TEST_BASE64}}" > book.zip.base64
          cat book.zip.base64 | base64 -d > book.zip
          unzip book.zip
          pwd
          ls -l book*
